version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_URL_BACKEND=https://crashalertai-backend.onrender.com
    ports:
      - "80:80"  # Match Nginx port
    depends_on:
      - backend

  # MongoDB (only for local testing; use Atlas in production)
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: