version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@cluster0.mongodb.net/crashalert?retryWrites=true&w=majority
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Map container's 80 to host's 3000
    environment:
      - REACT_APP_URL_BACKEND=https://crashalertai-backend.onrender.com
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  # MongoDB (only for local testing; use Atlas in production)
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: