version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-frontend:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: frontend
      - run:
          name: Run frontend tests
          command: |
            cd frontend
            npm test -- --watchAll=false

  test-backend:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: backend
      - run:
          name: Run backend tests
          command: |
            cd backend
            npm test
    
  test-model-service:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd model-service
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install -r test_requirements.txt
      - run:
          name: Run model service tests
          command: |
            cd model-service
            ./run_tests.sh

  deploy-via-ssh:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints: []
      - run:
          name: Deploy to server
          command: |
            ssh -o StrictHostKeyChecking=no root@138.199.216.9 '
              cd ~/CrashAlertAI &&
              git pull origin main &&
              docker compose down &&
              docker compose up -d --build --remove-orphans
            '

workflows:
  test-and-deploy:
    jobs:
      - test-frontend
      - test-backend
      - test-model-service
      - deploy-via-ssh:
          requires:
            - test-frontend
            - test-backend
            - test-model-service
          filters:
            branches:
              only: main
