version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-frontend:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: frontend
      - run:
          name: Run frontend tests
          command: |
            cd frontend
            npm test -- --watchAll=false

  test-backend:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: backend
      - run:
          name: Run backend tests
          command: |
            cd backend
            npm test
    
  test-model-service:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project
    environment:
      SERVICE_ACCOUNT_FILE: /app/credentials/drive_sa.json
    steps:
      - checkout

      - run:
          name: Restore Google Drive Credentials
          command: |
            sudo mkdir -p /app/credentials
            echo "$GOOGLE_DRIVE_SA_B64" | base64 -d | sudo tee /app/credentials/drive_sa.json > /dev/null

      - run:
          name: Install dependencies
          command: |
            cd model-service
            python -m venv venv
            source venv/bin/activate
            pip install --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt
            pip install -r test_requirements.txt

      - run:
          name: Run model service tests
          command: |
            cd model-service
            ./run_tests.sh

  deploy-via-ssh:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints: []
      - run:
          name: Deploy to server
          command: |
            export COMPOSE_BAKE=true
            export NODE_ENV=production
            ssh -o StrictHostKeyChecking=no root@138.199.216.9 '
              cd ~/CrashAlertAI &&
              git pull origin main &&
              docker compose down &&
              docker system prune -af &&  # Clean unused images
              docker compose up -d --build --remove-orphans
            '

workflows:
  test-and-deploy:
    jobs:
      - test-frontend
      - test-backend
      - test-model-service
      - deploy-via-ssh:
          requires:
            - test-frontend
            - test-backend
            - test-model-service
          filters:
            branches:
              only: main
